// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUlSDnFgunxAcIYxYsa3W_6YKp-5rnQCc',
    appId: '1:743224323840:web:583baced2ae77c84964de5',
    messagingSenderId: '743224323840',
    projectId: 'pokedex-8e228',
    authDomain: 'pokedex-8e228.firebaseapp.com',
    storageBucket: 'pokedex-8e228.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2-FryZ5ebydT8hmkpsBJtfcX5dm6mUhI',
    appId: '1:743224323840:android:39ab498c73d787fa964de5',
    messagingSenderId: '743224323840',
    projectId: 'pokedex-8e228',
    storageBucket: 'pokedex-8e228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzahdvocn-DeUGBIFB4qYnP0GtK6d9NwM',
    appId: '1:743224323840:ios:ae638039a608411a964de5',
    messagingSenderId: '743224323840',
    projectId: 'pokedex-8e228',
    storageBucket: 'pokedex-8e228.firebasestorage.app',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzahdvocn-DeUGBIFB4qYnP0GtK6d9NwM',
    appId: '1:743224323840:ios:ae638039a608411a964de5',
    messagingSenderId: '743224323840',
    projectId: 'pokedex-8e228',
    storageBucket: 'pokedex-8e228.firebasestorage.app',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUlSDnFgunxAcIYxYsa3W_6YKp-5rnQCc',
    appId: '1:743224323840:web:9dd3e8072f0340e6964de5',
    messagingSenderId: '743224323840',
    projectId: 'pokedex-8e228',
    authDomain: 'pokedex-8e228.firebaseapp.com',
    storageBucket: 'pokedex-8e228.firebasestorage.app',
  );
}
